"""
Django settings for translator project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from telnetlib import LOGOUT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = Path(__file__).resolve().parent.parent

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

"""
Cookie domains hardcoded to a production domain cause login/CSRF issues when
developing on localhost/127.0.0.1 because the browser will not send or accept
cookies for a different domain. Make this environment-aware.
Set DJANGO_ENV=production on the server to enable the production domains.
"""
DJANGO_ENV = os.getenv("DJANGO_ENV", "development").lower()
if DJANGO_ENV == "production":
    SESSION_COOKIE_DOMAIN = ".transfile.com.tr"
    CSRF_COOKIE_DOMAIN = ".transfile.com.tr"
    CSRF_TRUSTED_ORIGINS = [
        "https://transfile.com.tr",
        "https://*.transfile.com.tr",
    ]
else:
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://127.0.0.1",
    ]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jj)@hokpt(b_yd^xiceqei@(xpd3(&__34o3a4b*^)s0^3v4n0'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = [
    "transfile.com.tr",
    "www.transfile.com.tr",
    "localhost",
    "127.0.0.1",
    ".localhost",          
    "en.transfile.com.tr",
    "tr.transfile.com.tr",
    "de.transfile.com.tr",
    "fr.transfile.com.tr",
    "es.transfile.com.tr",
    "it.transfile.com.tr",
    "ru.transfile.com.tr",
    "ja.transfile.com.tr",
]



CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGE_CODE = "en"   # Using generic English as default

LANGUAGES = [
    ("en", "English"),
    ("tr", "Turkish"),
    ("de", "German"),
    ("fr", "French"),
    ("es", "Spanish"),
    ("it", "Italian"),
    ("ru", "Russian"),
    ("ja", "Japanese"),

]

LOCALE_PATHS = [
    BASE_DIR / "locale",   # where translation files live
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts', 
    'translate',
    # 'wallet', no need to add this since we added the config
    'wallet.apps.WalletConfig',
    'documents',
    "blog",
    "parler",
    "ckeditor",

]



PARLER_LANGUAGES = {
    None: (
        {"code": "en"},
        {"code": "tr"},
        {"code": "de"},
        {"code": "fr"},
        {"code": "es"},
        {"code": "it"},
        {"code": "ru"},
        {"code": "ja"},

    ),
    "default": {
        "fallbacks": ["en"],
        "hide_untranslated": False,
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    "middlewares.middleware.SubdomainInLanguageMiddleware",
]

ROOT_URLCONF = 'translator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'translator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'


# Media files (user uploads)
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATIC_ROOT = '/home/transfile/htdocs/www.transfile.com.tr/static/'  # full path for collected static files
MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/transfile/htdocs/www.transfile.com.tr/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'